### PR TITLE
fix(message): update lastMessage for chat indicator

### LINKED ISSUE #450: Update lastMessageDate when entering chat
Same number of unread messages appear after restarting app

### PR DESCRIPTION
**Pull request by olastor**
should fix #450

### CODE REVIEW

File: src/app/message/message.component.ts [hunk 1]
```diff
@@ -97,6 +97,10 @@ export class MessageComponent implements OnInit, OnDestroy {
           this.noMorePages = true;
         }
 
+        if (data.length >= 1) {
+          this.messageService.setLastMessage(data[data.length - 1].createdAt.toString());
```
Comment (binarious) [inline src/app/message/message.component.ts]: `synchronize` also adds messages. I think it needs this, too.
