### PR TITLE
fix: play sound on phones

### LINKED ISSUE #113: Timer bell on smartphones not working
> In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled - [Apple](https://developer.apple.com/library/safari/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html)

Chrome has the same policy

### PR DESCRIPTION
**Pull request by olastor**
Fixes #113

### CODE REVIEW

File: src/app/meditation/meditation.component.ts [hunk 1]
```diff
@@ -303,7 +312,13 @@ export class MeditationComponent {
     this.userService.getProfile()
       .map(res => res.json())
       .subscribe(
-        data => { console.log(data); this.profile = data; },
+        data => {
+          console.log(data);
```
Comment (binarious) [inline src/app/meditation/meditation.component.ts]: Please remove.
