### PR TITLE
fix: reactivate tabs after meditation end

### LINKED ISSUE #244: this page is disabled during meditation
On my android phone, after having completed a session and selecting the chat tab, it still displays the message "This page is disabled during meditation".  Only closing the webapp out of memory "resets" this.

### PR DESCRIPTION
**Pull request by olastor**
fixes #244

### CODE REVIEW

File: src/app/meditation/meditation.component.ts [hunk 1]
```diff
@@ -90,6 +90,12 @@ export class MeditationComponent {
     this.ownSession = this.activeMeditations && this.activeMeditations
       .filter(val => (<any>val).user._id === this.getUserId())
       .reduce((prev, val) => val, null);
+
+    if (this.ownSession){
```
Comment (binarious) [inline src/app/meditation/meditation.component.ts]: `this.appState.set('isMeditating', !!this.ownSession);`
