### PR TITLE
Fix/schedule

### LINKED ISSUE #355: Save hour difference from admin interface as own variable in database

### LINKED ISSUE #413: Schedule time conversion
Time displayed wrongly in list view as "UTC". Conversion from EDT to UTC/current timezone possibly wrong.

### PR DESCRIPTION
**Pull request by olastor**
depends on https://github.com/Sirimangalo/meditation-plus-server/pull/127

closes #413 
closes #355

### CODE REVIEW

File: src/app/admin/appointment/appointment-admin.component.ts [hunk 1]
```diff
@@ -46,21 +44,15 @@ export class AppointmentAdminComponent {
    * @return {string}      Local hour in format 'HH:mm'
    */
   printHour(hour: number): string {
-    // add increment
-    const hourNew = this.calcHour(hour, this.addHours);
+    let hourNew = hour + this.increment * 100;
+    hourNew = hourNew < 0 || hourNew >= 2400 ? 0 : hourNew;
```
Comment (binarious) [inline src/app/admin/appointment/appointment-admin.component.ts]: Is this really correct? If `hour` is at 2300 and `increment` at 3 then it should result in 0200, shouldn't it?

File: src/app/appointment/appointment.component.ts [hunk 2]
```diff
@@ -216,14 +233,14 @@ export class AppointmentComponent implements OnInit, OnDestroy {
     }
 
     // read time for EST/EDT timezone
-    const eastern = moment.tz(this.printHour(hour), 'HH:mm', 'America/Toronto');
+    const eastern = moment.tz(this.printHour(hour ), 'HH:mm', 'America/Toronto');
```
Comment (binarious) [inline src/app/appointment/appointment.component.ts]: revert pls

File: src/app/appointment/appointment.component.ts [hunk 3]
```diff
@@ -254,11 +272,14 @@ export class AppointmentComponent implements OnInit, OnDestroy {
...
-        res => this.profile,
+        res => {
+          this.profile = res;
+          this.localTimezone = this.getLocalTimezone();
+        },
         err => console.log(err)
       );
 
-    this.localTimezone = this.getLocalTimezone();
+    console.log(moment.tz('America/Toronto').format('z'));
```
Comment (binarious) [inline src/app/appointment/appointment.component.ts]: Please remove debug statements.

File: src/app/admin/appointment/appointment-admin.component.ts (hunk 1 above)
Comment (olastor) [inline src/app/admin/appointment/appointment-admin.component.ts]: No because it would then be displayed as being the same day at 02:00, meaning earlier than 23:00 (since the day is selected seperately)

Comment (binarious) [inline src/app/admin/appointment/appointment-admin.component.ts]: I see.
